# Generated by Django 4.1.6 on 2023-02-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField()),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('faculty', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
